spring:
  datasource:
    # 数据源基础配置
    username: root
    password: 3145guofu
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql//localhost:3306/test
    type: com.alibaba.druid.pool.DruidDataSource

    # 数据源其他配置
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多长时间进行一次检测，检测需要关闭的空闲连接，单位毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小的生存时间，单位毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计的filters，去掉监控界面的sql无法统计，'wail'同于防火强
    filters: stat,wall,logback
    # 通过connectionProperties属性打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000


